[project]
site_name = "sunwhere"
site_description = "Fast and accurate solar position calculations for solar resource assessment"
site_url = "https://jararias.github.io/sunwhere"
repo_url = "https://github.com/jararias/sunwhere"
site_author = "Jose A Ruiz-Arias"
nav = [
    {"Home" = "index.md"},
    {"Installation" = "installation.md"},
    {"User Guide" = "user-guide.md"},
    {"Quick Reference" = "quick-reference.md"},
    {"API Reference" = "api.md"},
]
extra_css = ["stylesheets/extra.css"]

[project.theme]
custom_dir = "overrides"
logo = "images/headerfig_Microsoft_Sans_Serif_black_on_transparent.png"
features = [
    "content.code.copy",      # Añade un botón flotante para copiar el código
    "content.code.select",    # Permite al usuario seleccionar rangos de líneas
    "content.code.annotate",  # Habilita notas explicativas flotantes dentro del código
    "navigatio.footer",       # Include links to the previous and next pages in the footer
]

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "orange"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "indigo"
accent = "orange"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[[project.theme.social]]
icon = "fontawesome/solid/envelope"
link = "mailto:jararias@uma.es"
name = "Jose A Ruiz-Arias, Universidad de Málaga, Spain"

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]
inventories = [
    "https://docs.python.org/3/objects.inv",
    "http://pandas.pydata.org/pandas-docs/stable/objects.inv",
    "https://docs.xarray.dev/en/stable/objects.inv",
    "https://numpy.org/doc/stable/objects.inv"
]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "numpy"
backlinks = "tree"
docstring_options = { "ignore_init_summary" = true }
docstring_section_style = "list"
filters = "public"
heading_level = 3
inherited_members = true
merge_init_into_class = true
parameter_headings = true
separate_signature = true
show_root_heading = true
show_root_full_path = false
show_signature_annotations = true
show_source = true
show_symbol_type_heading = true
show_symbol_type_toc = true
signature_crossrefs = true
summary = true
unwrap_annotated = true

[code]
# Resaltado de sintaxis
highlight_theme = "monokai"
line_numbers = true

[project.markdown_extensions.admonition]

[project.markdown_extensions.footnotes]

[project.markdown_extensions.pymdownx.blocks.caption]
prepend = true

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.attr_list]

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true  # Hace que las pestañas se vean más modernas y limpias